name: ugd2_c_kelompok6
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
    sdk: '>=3.1.1 <4.0.0'

dependencies:
    flutter:
        sdk: flutter
    flutter_slidable: ^0.6.0
    fluttertoast: ^8.2.2
    google_fonts: ^6.0.0
    image_picker: ^1.0.4
    input_history_text_field: ^0.2.0
    intl: ^0.18.1
    path: ^1.8.3
    shared_preferences: ^2.0.6
    speech_to_text: ^6.4.0
    sqflite: ^2.0.0
    geolocator: ^10.1.0
    geocoding: ^2.1.1
    qr_code_scanner: ^1.0.1
    mobile_scanner: ^3.2.0
    qr_flutter: ^4.1.0
    responsive_sizer: ^3.2.0
    pdf: ^3.10.6

dev_dependencies:
    flutter_lints: ^2.0.0
    flutter_test:
        sdk: flutter

flutter:
    assets:
        - images/

    fonts:
        - family: Raleway
          fonts:
              - asset: fonts/Raleway-Regular.ttf
              - asset: fonts/Raleway-Italic.ttf
                style: italic
        - family: Poppins
          fonts:
              - asset: fonts/Poppins-Regular.ttf
              - asset: fonts/Poppins-Bold.ttf
                weight: 700
        - family: Helvetica
          fonts:
              - asset: fonts/Helvetica.ttf
              - asset: fonts/Helvetica-Bold.ttf
                weight: 700

    uses-material-design: true
